### ISSUE TITLE
CleanMyMac (Setapp) 最新版无法注入

### ISSUE THREAD

**Issue by shirok1** [QiuChenly/InjectLib#60]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

```
chmod: /Applications/Setapp/CleanMyMac X.app: No such file or directory
xattr: No such file: /Applications/Setapp/CleanMyMac X.app
Traceback (most recent call last):
  File "/Volumes/Code/InjectLib/main.py", line 464, in <module>
    main()
    ~~~~^^
  File "/Volumes/Code/InjectLib/main.py", line 320, in main
    ["sudo", "pkill", "-f", getAppMainExecutable(app_base_locate)]
                            ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Volumes/Code/InjectLib/main.py", line 127, in getAppMainExecutable
    with open(f"{app_base}/Contents/Info.plist", "rb") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Setapp/CleanMyMac X.app/Contents/Info.plist'
```

疑似因为 .app 已改名为 CleanMyMac.app

手动修改 config.json 依然无法工作

```
cp: /Applications/Setapp/CleanMyMac.app/Contents/Frameworks/Announcements.framework/Versions/A/Announcements: No such file or directory
Traceback (most recent call last):
  File "/Volumes/Code/InjectLib/main.py", line 464, in <module>
    main()
    ~~~~^^
  File "/Volumes/Code/InjectLib/main.py", line 372, in main
    f"{app_base_locate}{i}/Contents/MacOS/{getAppMainExecutable(app_base_locate+i)}"
                                           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Code/InjectLib/main.py", line 127, in getAppMainExecutable
    with open(f"{app_base}/Contents/Info.plist", "rb") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Setapp/CleanMyMac.app/Contents/Library/LoginItems/CleanMyMac Menu.app/Contents/Info.plist'
```

### 最小复现

1. 安装 Setapp 并注入 com.setapp.DesktopClient
2. 用 Setapp 安装 CleanMyMac
3. 注入 com.macpaw.CleanMyMac-setapp

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
OS: macOS 15.1
CPU: M1
Memory: 16 GB
```

### 期望行为

能完成注入并激活

### 额外信息

https://qiuchenlyopensource.github.io/Documentaions/setapp.html#reinject-after-updating-or-downloading 没太看懂这句话意思是重新执行 main.py 注入 com.setapp.DesktopClient 吗

**Comment by QiuChenly** [comment]
这个app现在不是通杀的 新版本他们改动很大 文档已经过时。

**Comment by Parsifa1** [comment]
@shirok1 下载 [这个](https://macpaw.com/zh/download/cleanmymac) 包， 我测试过 应该是可以成功注入的

**Comment by QiuChenly** [comment]
也可以考虑从频道里找到打包好的版本直接可以激活。

**Comment by QiuChenly** [comment]
目前已经不再继续支持这个app，这个app臃肿难用。
